version: '3.8'

services:
  gateway:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-gateway-rest:latest
    build:
      dockerfile: src/Pb.ApiGateway/Dockerfile
      context: .
    ports:
      - 5000:80
    depends_on:
      - search
      - profile
    networks:
      - app-network
  search:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-search-rest:latest
    build: 
      dockerfile: src/Pb.Search.Service/Dockerfile
      context: .
    depends_on:
      - geo
      - rate
    networks:
      - app-network
  profile:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-profile-rest:latest
    build:
      dockerfile: src/Pb.Profile.Service/Dockerfile
      context: .
    networks:
      - app-network
  geo:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-geo-rest:latest
    build:
      dockerfile: src/Pb.Geo.Service/Dockerfile
      context: .
    networks:
      - app-network
  rate:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-rate-rest:latest
    build:
      dockerfile: src/Pb.Rate.Service/Dockerfile
      context: .
    networks:
      - app-network

networks:
  app-network: