version: '3.8'

services:
  gateway:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/java-gateway-grpc:latest
    build:
      dockerfile: Dockerfile
      context: ./gateway
    ports:
      - "5000:8080"
    depends_on:
      - search
      - profile
    networks:
      - app-network
  search:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/java-search-grpc:latest
    build:
      dockerfile: Dockerfile
      context: ./search
    depends_on:
      - geo
      - rate
    networks:
      - app-network

  profile:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/java-profile-grpc:latest
    build:
      dockerfile: Dockerfile
      context: ./profile
    networks:
      - app-network
  geo:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/java-geo-grpc:latest
    build:
      dockerfile: Dockerfile
      context: ./geo
    networks:
      - app-network
  rate:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/java-rate-grpc:latest
    build:
      dockerfile: Dockerfile
      context: ./rate
    networks:
      - app-network

networks:
  app-network: